// Demo data for previewing the app without Supabase

export const isDemoMode = () => {
  return !import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_ANON_KEY;
};

export const mockFarms = [
  {
    id: 'demo-1',
    slug: 'auto-sugarcane-farm-compact-design',
    title: 'Auto Sugarcane Farm - Compact Design',
    description: 'A highly efficient auto sugarcane farm using observers and pistons. Produces up to 2000 sugarcane per hour. Works perfectly in survival mode. This is a demo farm to showcase the design!',
    platform: ['Java', 'Bedrock'],
    versions: ['Java 1.21.1', 'Java 1.20.6', 'Bedrock 1.21.0'],
    tags: ['auto-sugarcane', 'redstone', 'easy', 'efficient'],
    materials: [
      { name: 'Observer', count: 8 },
      { name: 'Piston', count: 8 },
      { name: 'Redstone Dust', count: 16 },
      { name: 'Hopper', count: 4 },
      { name: 'Chest', count: 1 },
    ],
    optional_materials: [
      { name: 'Building Blocks', count: 20 },
    ],
    estimated_time: 15,
    chunk_requirements: 'Works in any chunk',
    notes: 'Make sure to place observers facing the sugar cane.',
    upvotes_count: 127,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    preview_image: 'https://images.unsplash.com/photo-1606503153255-59d8b8c73883?w=800&q=80',
    images: [],
    video_url: null,
    steps: [
      {
        title: 'Prepare the Area',
        description: 'Clear a 8x8 area and level the ground. Make sure you have water source nearby.',
        order: 0,
      },
      {
        title: 'Place Observers',
        description: 'Place observers facing the sugar cane rows. They will detect when sugar cane grows.',
        order: 1,
      },
      {
        title: 'Connect Redstone',
        description: 'Connect the observers to pistons using redstone dust.',
        order: 2,
      },
    ],
    users: {
      username: 'DemoFarmer',
      avatar_url: null,
    },
    author_id: 'demo-user',
    public: true,
  },
  {
    id: 'demo-2',
    slug: 'iron-golem-farm-400-iron-per-hour',
    title: 'Iron Golem Farm - 400+ Iron/Hour',
    description: 'Massive iron farm using villager mechanics. Produces iron ingots, poppies, and experience. Requires villagers and zombie for maximum efficiency.',
    platform: ['Java'],
    versions: ['Java 1.21.1', 'Java 1.20.6'],
    tags: ['iron-farm', 'mob-farm', 'xp-farm', 'villager'],
    materials: [
      { name: 'Villager', count: 3 },
      { name: 'Zombie', count: 1 },
      { name: 'Bed', count: 3 },
      { name: 'Obsidian', count: 64 },
    ],
    optional_materials: [
      { name: 'Nametag', count: 4 },
    ],
    estimated_time: 120,
    chunk_requirements: 'Build at least 100 blocks away from other villagers',
    height_requirements: 'Build above Y level 120',
    notes: 'Requires patience to transport villagers.',
    upvotes_count: 89,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    preview_image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&q=80',
    images: [],
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    steps: null,
    users: {
      username: 'RedstoneMaster',
      avatar_url: null,
    },
    author_id: 'demo-user-2',
    public: true,
  },
  {
    id: 'demo-3',
    slug: 'gold-farm-nether-portal-based',
    title: 'Gold Farm - Nether Portal Based',
    description: 'Efficient gold and XP farm using zombified piglin mechanics. Uses portal ticking for maximum spawn rates.',
    platform: ['Java'],
    versions: ['Java 1.21.1', 'Java 1.20.6'],
    tags: ['gold-farm', 'mob-farm', 'xp-farm', 'nether'],
    materials: [
      { name: 'Obsidian', count: 256 },
      { name: 'Flint and Steel', count: 1 },
      { name: 'Hopper', count: 64 },
    ],
    optional_materials: [],
    estimated_time: 180,
    chunk_requirements: 'Build in Nether at least 128 blocks away from other portals',
    notes: 'Can produce massive amounts of gold.',
    upvotes_count: 156,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    preview_image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
    images: [],
    video_url: null,
    steps: null,
    users: {
      username: 'NetherExplorer',
      avatar_url: null,
    },
    author_id: 'demo-user-3',
    public: true,
  },
  {
    id: 'demo-4',
    slug: 'simple-crop-farm-auto-harvest',
    title: 'Simple Crop Farm - Auto Harvest',
    description: 'Basic automatic crop farm for wheat, carrots, potatoes, and beets. Uses villagers or pistons to harvest.',
    platform: ['Java', 'Bedrock'],
    versions: ['Java 1.21.1', 'Bedrock 1.21.0'],
    tags: ['crop-farm', 'auto-harvest', 'easy', 'villager'],
    materials: [
      { name: 'Villager', count: 1 },
      { name: 'Composter', count: 1 },
      { name: 'Farmland', count: 80 },
    ],
    optional_materials: [
      { name: 'Light Source', count: 10 },
    ],
    estimated_time: 30,
    notes: 'Villager will automatically plant and harvest crops.',
    upvotes_count: 234,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    preview_image: 'https://images.unsplash.com/photo-1606503153255-59d8b8c73883?w=800&q=80',
    images: [],
    video_url: null,
    steps: null,
    users: {
      username: 'FarmerJoe',
      avatar_url: null,
    },
    author_id: 'demo-user-4',
    public: true,
  },
  {
    id: 'demo-5',
    slug: 'mob-grinder-sky-platform-design',
    title: 'Mob Grinder - Sky Platform Design',
    description: 'Classic mob grinder built high in the sky. Collects drops from natural mob spawning. Works in any version.',
    platform: ['Java', 'Bedrock'],
    versions: ['Java 1.21.1', 'Bedrock 1.21.0', 'All versions'],
    tags: ['mob-farm', 'easy', 'drops'],
    materials: [
      { name: 'Cobblestone', count: 512 },
      { name: 'Water Bucket', count: 8 },
      { name: 'Hopper', count: 16 },
    ],
    optional_materials: [],
    estimated_time: 60,
    height_requirements: 'Build above Y level 200 for best results',
    notes: 'Make sure to light up surrounding area.',
    upvotes_count: 98,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    preview_image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
    images: [],
    video_url: null,
    steps: null,
    users: {
      username: 'SkyBuilder',
      avatar_url: null,
    },
    author_id: 'demo-user-5',
    public: true,
  },
  {
    id: 'demo-6',
    slug: 'kelp-farm-auto-smelting',
    title: 'Kelp Farm with Auto-Smelting',
    description: 'Fully automated kelp farm that grows, harvests, and smelts kelp into dried kelp. Perfect for fuel production!',
    platform: ['Java', 'Bedrock'],
    versions: ['Java 1.21.1', 'Bedrock 1.21.0'],
    tags: ['kelp-farm', 'auto-smelting', 'fuel', 'redstone'],
    materials: [
      { name: 'Observer', count: 4 },
      { name: 'Piston', count: 4 },
      { name: 'Hopper', count: 8 },
      { name: 'Furnace', count: 4 },
    ],
    optional_materials: [
      { name: 'Redstone Block', count: 8 },
    ],
    estimated_time: 45,
    notes: 'Great for creating an endless fuel source!',
    upvotes_count: 145,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    preview_image: 'https://images.unsplash.com/photo-1606503153255-59d8b8c73883?w=800&q=80',
    images: [],
    video_url: null,
    steps: null,
    users: {
      username: 'OceanBuilder',
      avatar_url: null,
    },
    author_id: 'demo-user-6',
    public: true,
  },
];

export const mockComments = [
  {
    id: 'demo-comment-1',
    farm_id: 'demo-1',
    user_id: 'demo-commenter-1',
    body: 'This farm works great! Built it yesterday and it\'s already producing tons of sugarcane.',
    parent_comment_id: null,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    edited_at: null,
    users: {
      username: 'HappyBuilder',
      avatar_url: null,
    },
  },
  {
    id: 'demo-comment-2',
    farm_id: 'demo-1',
    user_id: 'demo-commenter-2',
    body: 'Can this work on Bedrock edition?',
    parent_comment_id: null,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    edited_at: null,
    users: {
      username: 'BedrockPlayer',
      avatar_url: null,
    },
  },
];

