// Farm categories from AllFarms.txt
export const FARM_CATEGORIES = [
  'Wood Farm',
  'Rail Duper',
  'Falling Block Duper',
  'Scute Farm',
  'Skeleton Farm',
  'Moss Farm',
  'Potato Farm',
  'Bamboo Farm',
  'Basalt Farm',
  'Beetroot Farm',
  'Dripleaf Farm',
  'Wax Farm',
  'Carpet Duper',
  'Concrete Maker',
  'Leather Farm',
  'Wither Skeleton Farm',
  'Ice Farm',
  'Vine Farm',
  'Cocoa Bean Farm',
  'Chicken Farm',
  'Mushroom Farm',
  'Mob in Bucket Farm',
  'Mob Farm',
  'Cherry Wood Farm',
  'Cobweb Farm',
  'Bean Farm',
  'Cow Farm',
  'Fish Farm',
  'Sheep Farm',
  'Hoglin Farm',
  'Rabbit Farm',
  'Mob Head Farm',
  'Nether Wood Farm',
  'Root/Fungus Farm',
  'Nylium Converter',
  'Cactus Farm',
  'Squid Farm',
  'Coral Farm',
  'Dirt Farm',
  'String Farm',
  'Kelp Farm',
  'Ghast Farm',
  'Chorus Farm',
  'Endstone Farm',
  'Copper Converter',
  'Tall Grass Farm',
  'Clay Farm',
  'Flower Farm',
  'Sand Farm',
  'Glow Berry Farm',
  'Glow Ink Sac Farm',
  'Glow Lichen Farm',
  'Goat Horn Farm',
  'Apple Farm',
  'Gold Farm',
  'Grass Block Farm',
  'Wool Farm',
  'HOTV Raid Farm',
  'Hanging Root Farm',
  'Honey Farm',
  'Hoglin + Witch Farm',
  'Pumpkin Converter',
  'Lava Farm',
  'Tall Flower Farm',
  'Sea Pickle Farm',
  'Auto Brewer',
  'Mangrove Wood Farm',
  'Melon Farm',
  'Mud Farm',
  'Mangrove Root Farm',
  'Mushroom Block Farm',
  'Stew Farm',
  'Record Farm',
  'Sprout Farm',
  'Beacon Farm',
  'Froglight Farm',
  'Wheat Farm',
  'Phantom Farm',
  'Bone Meal Farm',
  'Podzol Farm',
  'Phantom Farms',
  'Blaze Farms',
  'Turtle Farm',
  'Powder Snow Farm',
  'Guardian Farm',
  'Pumpkin Farm',
  'Fox Farm',
  'Bartering Farm',
  'Zombie Farm',
  'Sculk Farm',
  'Warden Farm',
  'Pickle Farm',
  'Seagrass Farm',
  'Shulker Farm',
  'Breeding',
  'Snow Farm',
  'Magma Cream Farm',
  'Drowned Farm',
  'Slime Farm',
  'Cobble Farm',
  'Creeper Farm',
  'Iron Farm',
  'Nether Tree',
  'Sugar Cane Farm',
  'Sweet Berry Farm',
  'Witch Farm',
  'Torchflower Farm',
  'Trident Farm',
  'Water Bucket Farm',
  'Weeping Vine Farm',
  'Sponge Converter',
  'Wither Rose Farm',
  'Player Interaction',
  'Raid Farm',
];

// Helper function to get category slug from category name
export function getCategorySlug(category: string): string {
  return category
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

// Helper function to get category name from slug
export function getCategoryFromSlug(slug: string): string | null {
  const category = FARM_CATEGORIES.find(
    (cat) => getCategorySlug(cat) === slug
  );
  return category || null;
}

