// Load all Minecraft items from CSV
// This file will be populated with items from minecraft_items.csv

export const MINECRAFT_ITEMS = [
  'Acacia Boat',
  'Acacia Boat with Chest',
  'Acacia Button',
  'Acacia Door',
  'Acacia Fence',
  'Acacia Fence Gate',
  'Acacia Hanging Sign',
  'Acacia Leaves',
  'Acacia Log',
  'Acacia Planks',
  'Acacia Pressure Plate',
  'Acacia Sapling',
  'Acacia Sign',
  'Acacia Slab',
  'Acacia Stairs',
  'Acacia Trapdoor',
  'Acacia Wood',
  'Activator Rail',
  'Allium',
  'Amethyst Cluster',
  'Amethyst Shard',
  'Ancient Debris',
  'Andesite',
  'Andesite Slab',
  'Andesite Stairs',
  'Andesite Wall',
  'Angler Pottery Sherd',
  'Anvil',
  'Apple',
  'Archer Pottery Sherd',
  'Armadillo Scute',
  'Armor Stand',
  'Arms Up Pottery Sherd',
  'Arrow',
  'Azalea',
  'Azalea Leaves',
  'Azure Bluet',
  'Baked Potato',
  'Bamboo',
  'Bamboo Button',
  'Bamboo Door',
  'Bamboo Fence',
  'Bamboo Fence Gate',
  'Bamboo Hanging Sign',
  'Bamboo Mosaic',
  'Bamboo Mosaic Slab',
  'Bamboo Mosaic Stairs',
  'Bamboo Planks',
  'Bamboo Pressure Plate',
  'Bamboo Raft',
  'Bamboo Raft with Chest',
  'Bamboo Shoot',
  'Bamboo Sign',
  'Bamboo Slab',
  'Bamboo Stairs',
  'Bamboo Trapdoor',
  'Barrel',
  'Basalt',
  'Beacon',
  'Bee Nest',
  'Beehive',
  'Beetroot',
  'Beetroot Seeds',
  'Beetroot Soup',
  'Bell',
  'Big Dripleaf',
  'Birch Boat',
  'Birch Boat with Chest',
  'Birch Button',
  'Birch Door',
  'Birch Fence',
  'Birch Fence Gate',
  'Birch Hanging Sign',
  'Birch Leaves',
  'Birch Log',
  'Birch Planks',
  'Birch Pressure Plate',
  'Birch Sapling',
  'Birch Sign',
  'Birch Slab',
  'Birch Stairs',
  'Birch Trapdoor',
  'Birch Wood',
  'Black Banner',
  'Black Bed',
  'Black Bundle',
  'Black Candle',
  'Black Carpet',
  'Black Concrete',
  'Black Concrete Powder',
  'Black Dye',
  'Black Glazed Terracotta',
  'Black Harness',
  'Black Shulker Box',
  'Black Stained Glass',
  'Black Stained Glass Pane',
  'Black Terracotta',
  'Black Wool',
  'Blackstone',
  'Blackstone Slab',
  'Blackstone Stairs',
  'Blackstone Wall',
  'Blade Pottery Sherd',
  'Blast Furnace',
  'Blaze Powder',
  'Blaze Rod',
  'Block of Amethyst',
  'Block of Bamboo',
  'Block of Coal',
  'Block of Copper',
  'Block of Diamond',
  'Block of Emerald',
  'Block of Gold',
  'Block of Iron',
  'Block of Lapis Lazuli',
  'Block of Netherite',
  'Block of Quartz',
  'Block of Raw Copper',
  'Block of Raw Gold',
  'Block of Raw Iron',
  'Block of Redstone',
  'Block of Resin',
  'Block of Stripped Bamboo',
  'Blue Banner',
  'Blue Bed',
  'Blue Bundle',
  'Blue Candle',
  'Blue Carpet',
  'Blue Concrete',
  'Blue Concrete Powder',
  'Blue Dye',
  'Blue Egg',
  'Blue Glazed Terracotta',
  'Blue Harness',
  'Blue Ice',
  'Blue Orchid',
  'Blue Shulker Box',
  'Blue Stained Glass',
  'Blue Stained Glass Pane',
  'Blue Terracotta',
  'Blue Wool',
  'Bolt Armor Trim',
  'Bone',
  'Bone Block',
  'Bone Meal',
  'Book',
  'Book and Quill',
  'Bookshelf',
  'Bordure Indented Banner Pattern',
  'Bottle o\' Enchanting',
  'Bow',
  'Bowl',
  'Brain Coral',
  'Brain Coral Block',
  'Brain Coral Fan',
  'Bread',
  'Breeze Rod',
  'Brewer Pottery Sherd',
  'Brewing Stand',
  'Brick',
  'Brick Slab',
  'Brick Stairs',
  'Brick Wall',
  'Bricks',
  'Brown Banner',
  'Brown Bed',
  'Brown Bundle',
  'Brown Candle',
  'Brown Carpet',
  'Brown Concrete',
  'Brown Concrete Powder',
  'Brown Dye',
  'Brown Egg',
  'Brown Glazed Terracotta',
  'Brown Harness',
  'Brown Mushroom',
  'Brown Mushroom Block',
  'Brown Shulker Box',
  'Brown Stained Glass',
  'Brown Stained Glass Pane',
  'Brown Terracotta',
  'Brown Wool',
  'Brush',
  'Bubble Coral',
  'Bubble Coral Block',
  'Bubble Coral Fan',
  'Bucket',
  'Bucket of Axolotl',
  'Bucket of Cod',
  'Bucket of Pufferfish',
  'Bucket of Salmon',
  'Bucket of Tadpole',
  'Bucket of Tropical Fish',
  'Bundle',
  'Burn Pottery Sherd',
  'Bush',
  'Cactus',
  'Cactus Flower',
  'Cake',
  'Calcite',
  'Calibrated Sculk Sensor',
  'Campfire',
  'Candle',
  'Carrot',
  'Carrot on a Stick',
  'Cartography Table',
  'Carved Pumpkin',
  'Cauldron',
  'Chain',
  'Chainmail Boots',
  'Chainmail Chestplate',
  'Chainmail Helmet',
  'Chainmail Leggings',
  'Charcoal',
  'Cherry Boat',
  'Cherry Boat with Chest',
  'Cherry Button',
  'Cherry Door',
  'Cherry Fence',
  'Cherry Fence Gate',
  'Cherry Hanging Sign',
  'Cherry Leaves',
  'Cherry Log',
  'Cherry Planks',
  'Cherry Pressure Plate',
  'Cherry Sapling',
  'Cherry Sign',
  'Cherry Slab',
  'Cherry Stairs',
  'Cherry Trapdoor',
  'Cherry Wood',
  'Chest',
  'Chipped Anvil',
  'Chiseled Bookshelf',
  'Chiseled Copper',
  'Chiseled Deepslate',
  'Chiseled Nether Bricks',
  'Chiseled Polished Blackstone',
  'Chiseled Quartz Block',
  'Chiseled Red Sandstone',
  'Chiseled Resin Bricks',
  'Chiseled Sandstone',
  'Chiseled Stone Bricks',
  'Chiseled Tuff',
  'Chiseled Tuff Bricks',
  'Chorus Flower',
  'Chorus Fruit',
  'Clay',
  'Clay Ball',
  'Clock',
  'Closed Eyeblossom',
  'Coal',
  'Coal Ore',
  'Coarse Dirt',
  'Coast Armor Trim',
  'Cobbled Deepslate',
  'Cobbled Deepslate Slab',
  'Cobbled Deepslate Stairs',
  'Cobbled Deepslate Wall',
  'Cobblestone',
  'Cobblestone Slab',
  'Cobblestone Stairs',
  'Cobblestone Wall',
  'Cobweb',
  'Cocoa Beans',
  'Compass',
  'Composter',
  'Conduit',
  'Cooked Chicken',
  'Cooked Cod',
  'Cooked Mutton',
  'Cooked Porkchop',
  'Cooked Rabbit',
  'Cooked Salmon',
  'Cookie',
  'Copper Bulb',
  'Copper Door',
  'Copper Grate',
  'Copper Ingot',
  'Copper Ore',
  'Copper Trapdoor',
  'Cornflower',
  'Cracked Deepslate Bricks',
  'Cracked Deepslate Tiles',
  'Cracked Nether Bricks',
  'Cracked Polished Blackstone Bricks',
  'Cracked Stone Bricks',
  'Crafter',
  'Crafting Table',
  'Creaking Heart',
  'Creeper Charge Banner Pattern',
  'Creeper Head',
  'Crimson Button',
  'Crimson Door',
  'Crimson Fence',
  'Crimson Fence Gate',
  'Crimson Fungus',
  'Crimson Hanging Sign',
  'Crimson Hyphae',
  'Crimson Nylium',
  'Crimson Planks',
  'Crimson Pressure Plate',
  'Crimson Roots',
  'Crimson Sign',
  'Crimson Slab',
  'Crimson Stairs',
  'Crimson Stem',
  'Crimson Trapdoor',
  'Crossbow',
  'Crying Obsidian',
  'Cut Copper',
  'Cut Copper Slab',
  'Cut Copper Stairs',
  'Cut Red Sandstone',
  'Cut Red Sandstone Slab',
  'Cut Sandstone',
  'Cut Sandstone Slab',
  'Cyan Banner',
  'Cyan Bed',
  'Cyan Bundle',
  'Cyan Candle',
  'Cyan Carpet',
  'Cyan Concrete',
  'Cyan Concrete Powder',
  'Cyan Dye',
  'Cyan Glazed Terracotta',
  'Cyan Harness',
  'Cyan Shulker Box',
  'Cyan Stained Glass',
  'Cyan Stained Glass Pane',
  'Cyan Terracotta',
  'Cyan Wool',
  'Damaged Anvil',
  'Dandelion',
  'Danger Pottery Sherd',
  'Dark Oak Boat',
  'Dark Oak Boat with Chest',
  'Dark Oak Button',
  'Dark Oak Door',
  'Dark Oak Fence',
  'Dark Oak Fence Gate',
  'Dark Oak Hanging Sign',
  'Dark Oak Leaves',
  'Dark Oak Log',
  'Dark Oak Planks',
  'Dark Oak Pressure Plate',
  'Dark Oak Sapling',
  'Dark Oak Sign',
  'Dark Oak Slab',
  'Dark Oak Stairs',
  'Dark Oak Trapdoor',
  'Dark Oak Wood',
  'Dark Prismarine',
  'Dark Prismarine Slab',
  'Dark Prismarine Stairs',
  'Daylight Detector',
  'Dead Brain Coral',
  'Dead Brain Coral Block',
  'Dead Brain Coral Fan',
  'Dead Bubble Coral',
  'Dead Bubble Coral Block',
  'Dead Bubble Coral Fan',
  'Dead Bush',
  'Dead Coral Block',
  'Dead Fire Coral',
  'Dead Fire Coral Block',
  'Dead Fire Coral Fan',
  'Dead Horn Coral',
  'Dead Horn Coral Block',
  'Dead Horn Coral Fan',
  'Dead Tube Coral',
  'Dead Tube Coral Block',
  'Dead Tube Coral Fan',
  'Decorated Pot',
  'Deepslate',
  'Deepslate Brick Slab',
  'Deepslate Brick Stairs',
  'Deepslate Brick Wall',
  'Deepslate Bricks',
  'Deepslate Coal Ore',
  'Deepslate Copper Ore',
  'Deepslate Diamond Ore',
  'Deepslate Emerald Ore',
  'Deepslate Gold Ore',
  'Deepslate Iron Ore',
  'Deepslate Lapis Lazuli Ore',
  'Deepslate Redstone Ore',
  'Deepslate Tile Slab',
  'Deepslate Tile Stairs',
  'Deepslate Tile Wall',
  'Deepslate Tiles',
  'Detector Rail',
  'Diamond',
  'Diamond Axe',
  'Diamond Boots',
  'Diamond Chestplate',
  'Diamond Helmet',
  'Diamond Hoe',
  'Diamond Horse Armor',
  'Diamond Leggings',
  'Diamond Ore',
  'Diamond Pickaxe',
  'Diamond Shovel',
  'Diamond Sword',
  'Diorite',
  'Diorite Slab',
  'Diorite Stairs',
  'Diorite Wall',
  'Dirt',
  'Disc Fragment',
  'Dispenser',
  'Dragon Egg',
  'Dragon Head',
  'Dragon\'s Breath',
  'Dried Ghast',
  'Dried Kelp',
  'Dried Kelp Block',
  'Dripstone Block',
  'Dropper',
  'Dune Armor Trim',
  'Echo Shard',
  'Egg',
  'Elytra',
  'Emerald',
  'Emerald Ore',
  'Empty Map',
  'Enchanted Book',
  'Enchanted Golden Apple',
  'Enchanting Table',
  'End Crystal',
  'End Rod',
  'End Stone',
  'End Stone Brick Slab',
  'End Stone Brick Stairs',
  'End Stone Brick Wall',
  'End Stone Bricks',
  'Ender Chest',
  'Ender Pearl',
  'Explorer Pottery Sherd',
  'Exposed Chiseled Copper',
  'Exposed Copper',
  'Exposed Copper Bulb',
  'Exposed Copper Door',
  'Exposed Copper Grate',
  'Exposed Copper Trapdoor',
  'Exposed Cut Copper',
  'Exposed Cut Copper Slab',
  'Exposed Cut Copper Stairs',
  'Eye Armor Trim',
  'Eye of Ender',
  'Feather',
  'Fermented Spider Eye',
  'Fern',
  'Field Masoned Banner Pattern',
  'Fire Charge',
  'Fire Coral',
  'Fire Coral Block',
  'Fire Coral Fan',
  'Firefly Bush',
  'Firework Rocket',
  'Firework Star',
  'Fishing Rod',
  'Fletching Table',
  'Flint',
  'Flint and Steel',
  'Flow Armor Trim',
  'Flow Banner Pattern',
  'Flow Pottery Sherd',
  'Flower Charge Banner Pattern',
  'Flower Pot',
  'Flowering Azalea',
  'Flowering Azalea Leaves',
  'Friend Pottery Sherd',
  'Furnace',
  'Gear',
  'Ghast Tear',
  'Gilded Blackstone',
  'Glass',
  'Glass Bottle',
  'Glass Pane',
  'Glistering Melon Slice',
  'Globe Banner Pattern',
  'Glow Berries',
  'Glow Ink Sac',
  'Glow Item Frame',
  'Glow Lichen',
  'Glowstone',
  'Glowstone Dust',
  'Goat Horn',
  'Gold Ingot',
  'Gold Nugget',
  'Gold Ore',
  'Golden Apple',
  'Golden Axe',
  'Golden Boots',
  'Golden Carrot',
  'Golden Chestplate',
  'Golden Helmet',
  'Golden Hoe',
  'Golden Horse Armor',
  'Golden Leggings',
  'Golden Pickaxe',
  'Golden Shovel',
  'Golden Sword',
  'Granite',
  'Granite Slab',
  'Granite Stairs',
  'Granite Wall',
  'Grass Block',
  'Gravel',
  'Gray Banner',
  'Gray Bed',
  'Gray Bundle',
  'Gray Candle',
  'Gray Carpet',
  'Gray Concrete',
  'Gray Concrete Powder',
  'Gray Dye',
  'Gray Glazed Terracotta',
  'Gray Harness',
  'Gray Shulker Box',
  'Gray Stained Glass',
  'Gray Stained Glass Pane',
  'Gray Terracotta',
  'Gray Wool',
  'Green Banner',
  'Green Bed',
  'Green Bundle',
  'Green Candle',
  'Green Carpet',
  'Green Concrete',
  'Green Concrete Powder',
  'Green Dye',
  'Green Glazed Terracotta',
  'Green Harness',
  'Green Shulker Box',
  'Green Stained Glass',
  'Green Stained Glass Pane',
  'Green Terracotta',
  'Green Wool',
  'Grindstone',
  'Gunpowder',
  'Guster Banner Pattern',
  'Guster Pottery Sherd',
  'Hanging Roots',
  'Hay Bale',
  'Heart of the Sea',
  'Heart Pottery Sherd',
  'Heartbreak Pottery Sherd',
  'Heavy Core',
  'Heavy Weighted Pressure Plate',
  'Honey Block',
  'Honey Bottle',
  'Honeycomb',
  'Honeycomb Block',
  'Hopper',
  'Horn Coral',
  'Horn Coral Block',
  'Horn Coral Fan',
  'Horse Saddle',
  'Host Armor Trim',
  'Howl Pottery Sherd',
  'Ice',
  'Ink Sac',
  'Iron Axe',
  'Iron Bars',
  'Iron Boots',
  'Iron Chestplate',
  'Iron Door',
  'Iron Helmet',
  'Iron Hoe',
  'Iron Horse Armor',
  'Iron Ingot',
  'Iron Leggings',
  'Iron Nugget',
  'Iron Ore',
  'Iron Pickaxe',
  'Iron Shovel',
  'Iron Sword',
  'Iron Trapdoor',
  'Item Frame',
  'Jack o\'Lantern',
  'Jukebox',
  'Jungle Boat',
  'Jungle Boat with Chest',
  'Jungle Button',
  'Jungle Door',
  'Jungle Fence',
  'Jungle Fence Gate',
  'Jungle Hanging Sign',
  'Jungle Leaves',
  'Jungle Log',
  'Jungle Planks',
  'Jungle Pressure Plate',
  'Jungle Sapling',
  'Jungle Sign',
  'Jungle Slab',
  'Jungle Stairs',
  'Jungle Trapdoor',
  'Jungle Wood',
  'Ladder',
  'Lantern',
  'Lapis Lazuli',
  'Lapis Lazuli Ore',
  'Large Amethyst Bud',
  'Large Fern',
  'Lava Bucket',
  'Lava Spawner',
  'Lead',
  'Leaf Litter',
  'Leather',
  'Leather Boots',
  'Leather Cap',
  'Leather Horse Armor',
  'Leather Pants',
  'Leather Tunic',
  'Lectern',
  'Lever',
  'Light Blue Banner',
  'Light Blue Bed',
  'Light Blue Bundle',
  'Light Blue Candle',
  'Light Blue Carpet',
  'Light Blue Concrete',
  'Light Blue Concrete Powder',
  'Light Blue Dye',
  'Light Blue Glazed Terracotta',
  'Light Blue Harness',
  'Light Blue Shulker Box',
  'Light Blue Stained Glass',
  'Light Blue Stained Glass Pane',
  'Light Blue Terracotta',
  'Light Blue Wool',
  'Light Gray Banner',
  'Light Gray Bed',
  'Light Gray Bundle',
  'Light Gray Candle',
  'Light Gray Carpet',
  'Light Gray Concrete',
  'Light Gray Concrete Powder',
  'Light Gray Dye',
  'Light Gray Glazed Terracotta',
  'Light Gray Harness',
  'Light Gray Shulker Box',
  'Light Gray Stained Glass',
  'Light Gray Stained Glass Pane',
  'Light Gray Terracotta',
  'Light Gray Wool',
  'Light Weighted Pressure Plate',
  'Lightning Rod',
  'Lilac',
  'Lily of the Valley',
  'Lily Pad',
  'Lime Banner',
  'Lime Bed',
  'Lime Bundle',
  'Lime Candle',
  'Lime Carpet',
  'Lime Concrete',
  'Lime Concrete Powder',
  'Lime Dye',
  'Lime Glazed Terracotta',
  'Lime Harness',
  'Lime Shulker Box',
  'Lime Stained Glass',
  'Lime Stained Glass Pane',
  'Lime Terracotta',
  'Lime Wool',
  'Lingering Potion',
  'Locked chest',
  'Lodestone',
  'Loom',
  'Mace',
  'Magenta Banner',
  'Magenta Bed',
  'Magenta Bundle',
  'Magenta Candle',
  'Magenta Carpet',
  'Magenta Concrete',
  'Magenta Concrete Powder',
  'Magenta Dye',
  'Magenta Glazed Terracotta',
  'Magenta Harness',
  'Magenta Shulker Box',
  'Magenta Stained Glass',
  'Magenta Stained Glass Pane',
  'Magenta Terracotta',
  'Magenta Wool',
  'Magma Block',
  'Magma Cream',
  'Mangrove Boat',
  'Mangrove Boat with Chest',
  'Mangrove Button',
  'Mangrove Door',
  'Mangrove Fence',
  'Mangrove Fence Gate',
  'Mangrove Hanging Sign',
  'Mangrove Leaves',
  'Mangrove Log',
  'Mangrove Planks',
  'Mangrove Pressure Plate',
  'Mangrove Propagule',
  'Mangrove Roots',
  'Mangrove Sign',
  'Mangrove Slab',
  'Mangrove Stairs',
  'Mangrove Trapdoor',
  'Mangrove Wood',
  'Map',
  'Medium Amethyst Bud',
  'Melon',
  'Melon Seeds',
  'Melon Slice',
  'Milk Bucket',
  'Minecart',
  'Minecart with Chest',
  'Minecart with Furnace',
  'Minecart with Hopper',
  'Minecart with TNT',
  'Miner Pottery Sherd',
  'Moss Block',
  'Moss Carpet',
  'Mossy Cobblestone',
  'Mossy Cobblestone Slab',
  'Mossy Cobblestone Stairs',
  'Mossy Cobblestone Wall',
  'Mossy Stone Brick Slab',
  'Mossy Stone Brick Stairs',
  'Mossy Stone Brick Wall',
  'Mossy Stone Bricks',
  'Mourner Pottery Sherd',
  'Mud',
  'Mud Brick Slab',
  'Mud Brick Stairs',
  'Mud Brick Wall',
  'Mud Bricks',
  'Muddy Mangrove Roots',
  'Mushroom Stem',
  'Mushroom Stew',
  'Music Disc (11)',
  'Music Disc (13)',
  'Music Disc (5)',
  'Music Disc (blocks)',
  'Music Disc (cat)',
  'Music Disc (chirp)',
  'Music Disc (Creator (Music Box))',
  'Music Disc (Creator)',
  'Music Disc (far)',
  'Music Disc (Lava Chicken)',
  'Music Disc (mall)',
  'Music Disc (mellohi)',
  'Music Disc (otherside)',
  'Music Disc (Pigstep)',
  'Music Disc (Precipice)',
  'Music Disc (Relic)',
  'Music Disc (stal)',
  'Music Disc (strad)',
  'Music Disc (Tears)',
  'Music Disc (wait)',
  'Music Disc (ward)',
  'Mycelium',
  'Name Tag',
  'Nautilus Shell',
  'Nether Brick',
  'Nether Brick Fence',
  'Nether Brick Slab',
  'Nether Brick Stairs',
  'Nether Brick Wall',
  'Nether Bricks',
  'Nether Gold Ore',
  'Nether Quartz',
  'Nether Quartz Ore',
  'Nether Sprouts',
  'Nether Star',
  'Nether Wart',
  'Nether Wart Block',
  'Netherite Axe',
  'Netherite Boots',
  'Netherite Chestplate',
  'Netherite Helmet',
  'Netherite Hoe',
  'Netherite Ingot',
  'Netherite Leggings',
  'Netherite Pickaxe',
  'Netherite Scrap',
  'Netherite Shovel',
  'Netherite Sword',
  'Netherite Upgrade',
  'Netherrack',
  'Note Block',
  'Oak Boat',
  'Oak Boat with Chest',
  'Oak Button',
  'Oak Door',
  'Oak Fence',
  'Oak Fence Gate',
  'Oak Hanging Sign',
  'Oak Leaves',
  'Oak Log',
  'Oak Planks',
  'Oak Pressure Plate',
  'Oak Sapling',
  'Oak Sign',
  'Oak Slab',
  'Oak Stairs',
  'Oak Trapdoor',
  'Oak Wood',
  'Observer',
  'Obsidian',
  'Ochre Froglight',
  'Ominous Banner',
  'Ominous Bottle',
  'Ominous Trial Key',
  'Open Eyeblossom',
  'Orange Banner',
  'Orange Bed',
  'Orange Bundle',
  'Orange Candle',
  'Orange Carpet',
  'Orange Concrete',
  'Orange Concrete Powder',
  'Orange Dye',
  'Orange Glazed Terracotta',
  'Orange Harness',
  'Orange Shulker Box',
  'Orange Stained Glass',
  'Orange Stained Glass Pane',
  'Orange Terracotta',
  'Orange Tulip',
  'Orange Wool',
  'Oxeye Daisy',
  'Oxidized Chiseled Copper',
  'Oxidized Copper',
  'Oxidized Copper Bulb',
  'Oxidized Copper Door',
  'Oxidized Copper Grate',
  'Oxidized Copper Trapdoor',
  'Oxidized Cut Copper',
  'Oxidized Cut Copper Slab',
  'Oxidized Cut Copper Stairs',
  'Packed Ice',
  'Packed Mud',
  'Painting',
  'Pale Hanging Moss',
  'Pale Moss Block',
  'Pale Moss Carpet',
  'Pale Oak Boat',
  'Pale Oak Boat with Chest',
  'Pale Oak Button',
  'Pale Oak Door',
  'Pale Oak Fence',
  'Pale Oak Fence Gate',
  'Pale Oak Hanging Sign',
  'Pale Oak Leaves',
  'Pale Oak Log',
  'Pale Oak Planks',
  'Pale Oak Pressure Plate',
  'Pale Oak Sapling',
  'Pale Oak Sign',
  'Pale Oak Slab',
  'Pale Oak Stairs',
  'Pale Oak Trapdoor',
  'Pale Oak Wood',
  'Paper',
  'Pearlescent Froglight',
  'Peony',
  'Petrified Oak Slab',
  'Phantom Membrane',
  'Piglin Head',
  'Pink Banner',
  'Pink Bed',
  'Pink Bundle',
  'Pink Candle',
  'Pink Carpet',
  'Pink Concrete',
  'Pink Concrete Powder',
  'Pink Dye',
  'Pink Glazed Terracotta',
  'Pink Harness',
  'Pink Petals',
  'Pink Shulker Box',
  'Pink Stained Glass',
  'Pink Stained Glass Pane',
  'Pink Terracotta',
  'Pink Tulip',
  'Pink Wool',
  'Piston',
  'Pitcher Plant',
  'Pitcher Pod',
  'Plenty Pottery Sherd',
  'Podzol',
  'Pointed Dripstone',
  'Poisonous Potato',
  'Polished Andesite',
  'Polished Andesite Slab',
  'Polished Andesite Stairs',
  'Polished Basalt',
  'Polished Blackstone',
  'Polished Blackstone Brick Slab',
  'Polished Blackstone Brick Stairs',
  'Polished Blackstone Brick Wall',
  'Polished Blackstone Bricks',
  'Polished Blackstone Button',
  'Polished Blackstone Pressure Plate',
  'Polished Blackstone Slab',
  'Polished Blackstone Stairs',
  'Polished Blackstone Wall',
  'Polished Deepslate',
  'Polished Deepslate Slab',
  'Polished Deepslate Stairs',
  'Polished Deepslate Wall',
  'Polished Diorite',
  'Polished Diorite Slab',
  'Polished Diorite Stairs',
  'Polished Granite',
  'Polished Granite Slab',
  'Polished Granite Stairs',
  'Polished Tuff',
  'Polished Tuff Slab',
  'Polished Tuff Stairs',
  'Polished Tuff Wall',
  'Popped Chorus Fruit',
  'Poppy',
  'Potato',
  'Potion',
  'Powder Snow',
  'Powder Snow Bucket',
  'Powered Rail',
  'Prismarine',
  'Prismarine Brick Slab',
  'Prismarine Brick Stairs',
  'Prismarine Bricks',
  'Prismarine Crystals',
  'Prismarine Shard',
  'Prismarine Slab',
  'Prismarine Stairs',
  'Prismarine Wall',
  'Prize Pottery Sherd',
  'Pufferfish',
  'Pumpkin',
  'Pumpkin Pie',
  'Pumpkin Seeds',
  'Purple Banner',
  'Purple Bed',
  'Purple Bundle',
  'Purple Candle',
  'Purple Carpet',
  'Purple Concrete',
  'Purple Concrete Powder',
  'Purple Dye',
  'Purple Glazed Terracotta',
  'Purple Harness',
  'Purple Shulker Box',
  'Purple Stained Glass',
  'Purple Stained Glass Pane',
  'Purple Terracotta',
  'Purple Wool',
  'Purpur Block',
  'Purpur Pillar',
  'Purpur Slab',
  'Purpur Stairs',
  'Quartz Bricks',
  'Quartz Pillar',
  'Quartz Slab',
  'Quartz Stairs',
  'Rabbit Hide',
  'Rabbit Stew',
  'Rabbit\'s Foot',
  'Rail',
  'Raiser Armor Trim',
  'Raw Beef',
  'Raw Chicken',
  'Raw Cod',
  'Raw Copper',
  'Raw Gold',
  'Raw Iron',
  'Raw Mutton',
  'Raw Porkchop',
  'Raw Rabbit',
  'Raw Salmon',
  'Recovery Compass',
  'Red Banner',
  'Red Bed',
  'Red Bundle',
  'Red Candle',
  'Red Carpet',
  'Red Concrete',
  'Red Concrete Powder',
  'Red Dye',
  'Red Glazed Terracotta',
  'Red Harness',
  'Red Mushroom',
  'Red Mushroom Block',
  'Red Nether Brick Slab',
  'Red Nether Brick Stairs',
  'Red Nether Brick Wall',
  'Red Nether Bricks',
  'Red Sand',
  'Red Sandstone',
  'Red Sandstone Slab',
  'Red Sandstone Stairs',
  'Red Sandstone Wall',
  'Red Shulker Box',
  'Red Stained Glass',
  'Red Stained Glass Pane',
  'Red Terracotta',
  'Red Tulip',
  'Red Wool',
  'Redstone Comparator',
  'Redstone Dust',
  'Redstone Lamp',
  'Redstone Ore',
  'Redstone Repeater',
  'Redstone Torch',
  'Resin Brick',
  'Resin Brick Slab',
  'Resin Brick Stairs',
  'Resin Brick Wall',
  'Resin Bricks',
  'Resin Clump',
  'Respawn Anchor',
  'Rib Armor Trim',
  'Rooted Dirt',
  'Rose Bush',
  'Rotten Flesh',
  'Saddle',
  'Sand',
  'Sandstone',
  'Sandstone Slab',
  'Sandstone Stairs',
  'Sandstone Wall',
  'Scaffolding',
  'Scrape Pottery Sherd',
  'Sculk',
  'Sculk Catalyst',
  'Sculk Sensor',
  'Sculk Shrieker',
  'Sculk Vein',
  'Sea Lantern',
  'Sea Pickle',
  'Seagrass',
  'Sentry Armor Trim',
  'Shaper Armor Trim',
  'Sheaf Pottery Sherd',
  'Shears',
  'Shelter Pottery Sherd',
  'Shield',
  'Short Dry Grass',
  'Short Grass',
  'Shroomlight',
  'Shrub',
  'Shulker Box',
  'Shulker Shell',
  'Silence Armor Trim',
  'Skeleton Skull',
  'Skull Charge Banner Pattern',
  'Skull Pottery Sherd',
  'Slime Block',
  'Slimeball',
  'Small Amethyst Bud',
  'Small Dripleaf',
  'Smithing Table',
  'Smoker',
  'Smooth Basalt',
  'Smooth Quartz Block',
  'Smooth Quartz Slab',
  'Smooth Quartz Stairs',
  'Smooth Red Sandstone',
  'Smooth Red Sandstone Slab',
  'Smooth Red Sandstone Stairs',
  'Smooth Sandstone',
  'Smooth Sandstone Slab',
  'Smooth Sandstone Stairs',
  'Smooth Stone',
  'Smooth Stone Slab',
  'Sniffer Egg',
  'Snort Pottery Sherd',
  'Snout Armor Trim',
  'Snout Banner Pattern',
  'Snow',
  'Snow Block',
  'Snowball',
  'Soul Campfire',
  'Soul Fire',
  'Soul Lantern',
  'Soul Sand',
  'Soul Soil',
  'Soul Torch',
  'Spectral Arrow',
  'Spider Eye',
  'Spire Armor Trim',
  'Splash Potion',
  'Sponge',
  'Spore Blossom',
  'Spruce Boat',
  'Spruce Boat with Chest',
  'Spruce Button',
  'Spruce Door',
  'Spruce Fence',
  'Spruce Fence Gate',
  'Spruce Hanging Sign',
  'Spruce Leaves',
  'Spruce Log',
  'Spruce Planks',
  'Spruce Pressure Plate',
  'Spruce Sapling',
  'Spruce Sign',
  'Spruce Slab',
  'Spruce Stairs',
  'Spruce Trapdoor',
  'Spruce Wood',
  'Spyglass',
  'Steak',
  'Stick',
  'Sticky Piston',
  'Stone',
  'Stone Axe',
  'Stone Brick Slab',
  'Stone Brick Stairs',
  'Stone Brick Wall',
  'Stone Bricks',
  'Stone Button',
  'Stone Hoe',
  'Stone Pickaxe',
  'Stone Pressure Plate',
  'Stone Shovel',
  'Stone Slab',
  'Stone Stairs',
  'Stone Sword',
  'Stonecutter',
  'String',
  'Stripped Acacia Log',
  'Stripped Acacia Wood',
  'Stripped Birch Log',
  'Stripped Birch Wood',
  'Stripped Cherry Log',
  'Stripped Cherry Wood',
  'Stripped Crimson Hyphae',
  'Stripped Crimson Stem',
  'Stripped Dark Oak Log',
  'Stripped Dark Oak Wood',
  'Stripped Jungle Log',
  'Stripped Jungle Wood',
  'Stripped Mangrove Log',
  'Stripped Mangrove Wood',
  'Stripped Oak Log',
  'Stripped Oak Wood',
  'Stripped Pale Oak Log',
  'Stripped Pale Oak Wood',
  'Stripped Spruce Log',
  'Stripped Spruce Wood',
  'Stripped Warped Hyphae',
  'Stripped Warped Stem',
  'Studded Boots',
  'Studded Chestplate',
  'Studded Helmet',
  'Studded Leggings',
  'Sugar',
  'Sugar Cane',
  'Sunflower',
  'Suspicious Stew',
  'Sweet Berries',
  'Tall Dry Grass',
  'Tall Grass',
  'Target',
  'Terracotta',
  'Thing Banner Pattern',
  'Tide Armor Trim',
  'Tinted Glass',
  'Tipped Arrow',
  'TNT',
  'Torch',
  'Torchflower',
  'Torchflower Seeds',
  'Totem of Undying',
  'Trapped Chest',
  'Trial Key',
  'Trident',
  'Tripwire Hook',
  'Tropical Fish',
  'Tube Coral',
  'Tube Coral Block',
  'Tube Coral Fan',
  'Tuff',
  'Tuff Brick Slab',
  'Tuff Brick Stairs',
  'Tuff Brick Wall',
  'Tuff Bricks',
  'Tuff Slab',
  'Tuff Stairs',
  'Tuff Wall',
  'Turtle Egg',
  'Turtle Scute',
  'Turtle Shell',
  'Twisting Vines',
  'Verdant Froglight',
  'Vex Armor Trim',
  'Vines',
  'Ward Armor Trim',
  'Warped Button',
  'Warped Door',
  'Warped Fence',
  'Warped Fence Gate',
  'Warped Fungus',
  'Warped Fungus on a Stick',
  'Warped Hanging Sign',
  'Warped Hyphae',
  'Warped Nylium',
  'Warped Planks',
  'Warped Pressure Plate',
  'Warped Roots',
  'Warped Sign',
  'Warped Slab',
  'Warped Stairs',
  'Warped Stem',
  'Warped Trapdoor',
  'Warped Wart Block',
  'Water Bucket',
  'Water Spawner',
  'Waxed Block of Copper',
  'Waxed Chiseled Copper',
  'Waxed Copper Bulb',
  'Waxed Copper Door',
  'Waxed Copper Grate',
  'Waxed Copper Trapdoor',
  'Waxed Cut Copper',
  'Waxed Cut Copper Slab',
  'Waxed Cut Copper Stairs',
  'Waxed Exposed Chiseled Copper',
  'Waxed Exposed Copper',
  'Waxed Exposed Copper Bulb',
  'Waxed Exposed Copper Door',
  'Waxed Exposed Copper Grate',
  'Waxed Exposed Copper Trapdoor',
  'Waxed Exposed Cut Copper',
  'Waxed Exposed Cut Copper Slab',
  'Waxed Exposed Cut Copper Stairs',
  'Waxed Oxidized Chiseled Copper',
  'Waxed Oxidized Copper',
  'Waxed Oxidized Copper Bulb',
  'Waxed Oxidized Copper Door',
  'Waxed Oxidized Copper Grate',
  'Waxed Oxidized Copper Trapdoor',
  'Waxed Oxidized Cut Copper',
  'Waxed Oxidized Cut Copper Slab',
  'Waxed Oxidized Cut Copper Stairs',
  'Waxed Weathered Chiseled Copper',
  'Waxed Weathered Copper',
  'Waxed Weathered Copper Bulb',
  'Waxed Weathered Copper Door',
  'Waxed Weathered Copper Grate',
  'Waxed Weathered Copper Trapdoor',
  'Waxed Weathered Cut Copper',
  'Waxed Weathered Cut Copper Slab',
  'Waxed Weathered Cut Copper Stairs',
  'Wayfinder Armor Trim',
  'Weathered Chiseled Copper',
  'Weathered Copper',
  'Weathered Copper Bulb',
  'Weathered Copper Door',
  'Weathered Copper Grate',
  'Weathered Copper Trapdoor',
  'Weathered Cut Copper',
  'Weathered Cut Copper Slab',
  'Weathered Cut Copper Stairs',
  'Weeping Vines',
  'Wet Sponge',
  'Wheat',
  'Wheat Seeds',
  'White Banner',
  'White Bed',
  'White Bundle',
  'White Candle',
  'White Carpet',
  'White Concrete',
  'White Concrete Powder',
  'White Dye',
  'White Glazed Terracotta',
  'White Harness',
  'White Shulker Box',
  'White Stained Glass',
  'White Stained Glass Pane',
  'White Terracotta',
  'White Tulip',
  'White Wool',
  'Wild Armor Trim',
  'Wildflowers',
  'Wind Charge',
  'Wither Rose',
  'Wither Skeleton Skull',
  'Wolf Armor',
  'Wooden Axe',
  'Wooden Hoe',
  'Wooden Pickaxe',
  'Wooden Shovel',
  'Wooden Sword',
  'Written Book',
  'Yellow Banner',
  'Yellow Bed',
  'Yellow Bundle',
  'Yellow Candle',
  'Yellow Carpet',
  'Yellow Concrete',
  'Yellow Concrete Powder',
  'Yellow Dye',
  'Yellow Glazed Terracotta',
  'Yellow Harness',
  'Yellow Shulker Box',
  'Yellow Stained Glass',
  'Yellow Stained Glass Pane',
  'Yellow Terracotta',
  'Yellow Wool',
  'Zombie Head',
];

// Helper function to filter items based on search query
export function filterMinecraftItems(query: string): string[] {
  if (!query.trim()) return [];
  const lowerQuery = query.toLowerCase();
  return MINECRAFT_ITEMS.filter(item => 
    item.toLowerCase().includes(lowerQuery)
  ).slice(0, 10); // Limit to 10 results for performance
}

